services:
  api-gateway:
    image: ghcr.io/${IMAGE_NAME}:latest
    container_name: api-gateway-reshala
    ports:
      - "8180:8180"
    environment:
      - SERVER_PORT=8180
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_ENABLED=false

      - EUREKA_INSTANCE_HOSTNAME=api-gateway-reshala
      - JWT_ACCESS_SECRET=${JWT_SECRET}
      - SECURITY_SERVICE_URI=http://security-service-reshala:8181
      - ARCHIVE_SERVICE_URI=http://solution-archive-service-reshala:8185
      - DOZZlE_URI=http://dozzle-reshala:8080
      - RMQ_URI=http://rabbitmq-reshala:15672
      - MINIO_URI=http://minio-reshala:9001
    networks:
      - reshala-net
    restart: unless-stopped

networks:
  reshala-net:
    external: true