server:
  port: 8180

services:
  security-service:
    uri: ${SECURITY_SERVICE_URI:http://localhost:8181}
  solution-archive-service:
    uri: ${ARCHIVE_SERVICE_URI:http://localhost:8185}
  dozzle:
    uri: ${DOZZlE_URI:http://localhost:8888}

spring:
  application:
    name: api-gateway
  cloud:
    config:
      enabled: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  codec:
    max-in-memory-size: 10MB

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://${EUREKA_USER:eureka-user}:${EUREKA_PASSWORD:zvBGTYdMUJV7mpRs35YA}@${EUREKA_HOST:localhost}:8761/eureka/

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway,health,info

jwt:
  secret:
    access: ${JWT_ACCESS_SECRET:AZGEwiclv3fkxe9GYSpLdIiwbWc/AzkV1SQi3YPIiq+vIAfAzrha9Q8xv79f3G3rJRPjUf1Nn0xWZ3sNajZD7Q==}

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: TRACE

rabbitmq:
  admin:
    uri: ${RMQ_URI:http://localhost:15672}

minio:
  admin:
    uri: ${MINIO_URI:http://localhost:9001}